### ISSUE TITLE
Link dentro do modal para outro modal

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/reveal-modal#4]
@matheusgimenez encontrei um bug. Estou usando o plugin em um site com Woo onde a single abre dentro do modal. E nesse modal tem os produtos relacionados, que também abrem em modal. Mas quando isso acontece, um link em um modal para outro modal ele abre um modal dentro do outro, criando uma barra de rolagem para cada link aberto.

Observei que isso acontece com a opção Open pages with reveal modal in load marcada. Sem ela a página é direcionada para a single.php.

![print-git](https://cloud.githubusercontent.com/assets/1918474/11242807/3b607296-8deb-11e5-91ee-14cdd1a1f415.png)

**Comment by matheusgimenez** [comment]
Tenso. Vou resolver assim que possível..

**Comment by matheusgimenez** [comment]
Resolvido ano passado.
