### ISSUE TITLE
Atualizar descricao do Plugin no Repo

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/reveal-modal#7]
@matheusgimenez quero incluir uma descricao em PT_BR e EN mais detalhada e interessante para ajudar as pessoas a entenderem melhor como o plugin funciona.

**Comment by LuwkasLima** [comment]
Feito em Ingles

https://github.com/brasadesign/reveal-modal/pull/9

**Comment by matheusgimenez** [comment]
Já foi pro ar.
